import { Prospect } from '@/types';

export const mockProspects: Prospect[] = [
  {
    id: 'prospect-1',
    name: 'Michael Chen',
    companyName: 'Pacific Coast Developers',
    email: 'mchen@pacificcoastdev.com',
    phone: '+1-415-555-0123',
    industry: 'Real Estate Development',
    source: 'apollo',
    status: 'new',
    enrichmentScore: 85,
    tags: ['high-value', 'multifamily', 'warm-lead'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    // Link to demo client (will be matched by company name)
    clientId: 'demo-client-1', // This will be set when demo data initializes
  },
  {
    id: 'prospect-2',
    name: 'Sarah Johnson',
    companyName: 'Metro Property Group',
    email: 'sjohnson@metropg.com',
    phone: '+1-212-555-0456',
    industry: 'Property Management',
    source: 'zoominfo',
    status: 'contacted',
    enrichmentScore: 72,
    tags: ['commercial', 'high-value'],
    lastContactDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'demo-client-2',
  },
  {
    id: 'prospect-3',
    name: 'David Rodriguez',
    companyName: 'Summit Real Estate Investments',
    email: 'drodriguez@summitrei.com',
    phone: '+1-310-555-0789',
    industry: 'Real Estate Investment',
    source: 'real-estate-db',
    status: 'responded',
    enrichmentScore: 90,
    tags: ['residential', 'warm-lead', 'high-value'],
    lastContactDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'demo-client-3',
  },
  {
    id: 'prospect-4',
    name: 'Jennifer Williams',
    companyName: 'Coastal Development Partners',
    email: 'jwilliams@coastaldev.com',
    phone: '+1-619-555-0321',
    industry: 'Real Estate Development',
    source: 'apollo',
    status: 'new',
    enrichmentScore: 68,
    tags: ['commercial', 'multifamily'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-5',
    name: 'Robert Kim',
    companyName: 'Urban Living Properties',
    email: 'rkim@urbanliving.com',
    phone: '+1-206-555-0654',
    industry: 'Property Management',
    source: 'zoominfo',
    status: 'contacted',
    enrichmentScore: 55,
    tags: ['residential'],
    lastContactDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-6',
    name: 'Lisa Anderson',
    companyName: 'Premier Real Estate Holdings',
    email: 'landerson@premierreh.com',
    phone: '+1-404-555-0987',
    industry: 'Real Estate Investment',
    source: 'real-estate-db',
    status: 'new',
    enrichmentScore: 78,
    tags: ['high-value', 'commercial', 'warm-lead'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-7',
    name: 'James Martinez',
    companyName: 'Heritage Development Corp',
    email: 'jmartinez@heritagedev.com',
    phone: '+1-713-555-0147',
    industry: 'Real Estate Development',
    source: 'apollo',
    status: 'responded',
    enrichmentScore: 82,
    tags: ['multifamily', 'high-value'],
    lastContactDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-8',
    name: 'Amanda Taylor',
    companyName: 'Riverside Property Management',
    email: 'ataylor@riversidepm.com',
    phone: '+1-503-555-0258',
    industry: 'Property Management',
    source: 'zoominfo',
    status: 'contacted',
    enrichmentScore: 65,
    tags: ['residential', 'commercial'],
    lastContactDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-9',
    name: 'Christopher Lee',
    companyName: 'Elite Real Estate Ventures',
    email: 'clee@eliterev.com',
    phone: '+1-305-555-0369',
    industry: 'Real Estate Investment',
    source: 'real-estate-db',
    status: 'new',
    enrichmentScore: 75,
    tags: ['commercial', 'warm-lead'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-10',
    name: 'Michelle Brown',
    companyName: 'Apex Development Group',
    email: 'mbrown@apexdev.com',
    phone: '+1-303-555-0470',
    industry: 'Real Estate Development',
    source: 'apollo',
    status: 'converted',
    enrichmentScore: 88,
    tags: ['high-value', 'multifamily', 'warm-lead'],
    lastContactDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'client-converted-1',
  },
  {
    id: 'prospect-11',
    name: 'Daniel White',
    companyName: 'Cascade Property Solutions',
    email: 'dwhite@cascadeps.com',
    phone: '+1-206-555-0581',
    industry: 'Property Management',
    source: 'zoominfo',
    status: 'new',
    enrichmentScore: 60,
    tags: ['residential'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-12',
    name: 'Emily Davis',
    companyName: 'Horizon Real Estate Capital',
    email: 'edavis@horizonrec.com',
    phone: '+1-312-555-0692',
    industry: 'Real Estate Investment',
    source: 'real-estate-db',
    status: 'contacted',
    enrichmentScore: 70,
    tags: ['commercial', 'high-value'],
    lastContactDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-13',
    name: 'Kevin Wilson',
    companyName: 'Terra Development Partners',
    email: 'kwilson@terradev.com',
    phone: '+1-415-555-0703',
    industry: 'Real Estate Development',
    source: 'apollo',
    status: 'responded',
    enrichmentScore: 80,
    tags: ['multifamily', 'warm-lead'],
    lastContactDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-14',
    name: 'Nicole Garcia',
    companyName: 'Summit Property Services',
    email: 'ngarcia@summitps.com',
    phone: '+1-602-555-0814',
    industry: 'Property Management',
    source: 'zoominfo',
    status: 'new',
    enrichmentScore: 58,
    tags: ['residential', 'commercial'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prospect-15',
    name: 'Thomas Moore',
    companyName: 'Pacific Rim Real Estate',
    email: 'tmoore@pacificrimre.com',
    phone: '+1-714-555-0925',
    industry: 'Real Estate Investment',
    source: 'real-estate-db',
    status: 'unqualified',
    enrichmentScore: 45,
    tags: [],
    lastContactDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

