import { internalMutation } from "../_generated/server";

/**
 * Migration script to seed the database with comprehensive file type definitions
 * Run this once to populate the database with all standard document types
 */
export const seedFileTypeDefinitions = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existingDefinitions = [
      // ==========================================
      // APPRAISALS CATEGORY
      // ==========================================
      {
        fileType: 'Appraisal',
        category: 'Appraisals',
        keywords: [
          'appraisal',
          'appraisal report',
          'property appraisal',
          'valuation',
          'property value',
          'market value assessment',
          'property assessment',
          'real estate appraisal',
          'valuation certificate',
          'property worth',
        ],
        description:
          'Appraisals are formal property valuation documents that assess the market value of real estate assets. These documents are prepared by qualified appraisers or valuers and provide an independent assessment of property worth for lending, insurance, or investment purposes. Appraisals typically contain property descriptions including location, size, condition, and features. They include market analysis comparing the subject property to similar properties in the area. Appraisals may use various valuation methodologies including comparable sales approach, income approach, or cost approach. They provide a final opinion of value with supporting evidence and rationale. Appraisals are used by lenders to determine loan-to-value ratios and by investors to make informed decisions. They are distinct from informal estimates or broker price opinions as they follow professional standards and methodologies.',
        identificationRules: [
          'Look for "Appraisal" or "Valuation" in the document title or header',
          'Contains property description with address, size, and condition details',
          'Includes market analysis or comparable property data',
          'Provides a formal opinion of value or market value figure',
          'May reference valuation methodologies (comparable sales, income, cost approach)',
          'Often includes photographs of the property',
          'Contains appraiser or valuer credentials and signature',
          'May include limiting conditions and assumptions',
        ],
        categoryRules:
          'Appraisals should be categorized under "Appraisals". This is a generic appraisal category for valuations that do not specifically follow RICS RedBook standards.',
      },
      {
        fileType: 'RedBook Valuation',
        category: 'Appraisals',
        keywords: [
          'rics',
          'royal institution of chartered surveyors',
          'valuation report',
          'chartered surveyor',
          'property valuation',
          'market value',
          'valuation methodology',
          'vps',
          'vpga',
          'valuation standards',
          'redbook',
          'red book',
        ],
        description:
          'RICS RedBook valuation reports are professional property valuations conducted by RICS (Royal Institution of Chartered Surveyors) qualified surveyors following the RedBook standards. These are formal, standardized appraisals used for lending, financial reporting, and professional purposes. Note: Most RICS valuations follow RedBook standards even if "RedBook" is not explicitly mentioned in the document. These reports contain comprehensive property details including full address, tenure (freehold/leasehold), size (sq ft/sq m), condition assessment, and formal Market Value figures. They include surveyor professional qualifications, RICS membership numbers, valuation assumptions, and may reference specific valuation standards (VPS 1-5, VPGA guidelines). RedBook valuations are distinct from informal valuations, broker opinions, or automated valuation models and should always be categorized under Appraisals.',
        identificationRules: [
          'Look for "RICS" or "Royal Institution of Chartered Surveyors" branding or logos - this is the PRIMARY indicator',
          'Contains formal valuation methodology section (e.g., Comparable Method, Investment Method, Residual Method, Profits Method)',
          'Includes comprehensive property details: full address, tenure (freehold/leasehold), size (sq ft/sq m), condition assessment',
          'Provides a formal "Market Value" figure or other valuation basis (Investment Value, Fair Value, etc.)',
          'Contains surveyor\'s professional qualifications, RICS membership numbers, or registration details',
          'May include "Valuation Assumptions" and "Special Assumptions" sections',
          'May reference specific valuation standards (VPS 1-5, VPGA guidelines)',
          'Often includes limiting conditions, disclaimers, and scope of work sections',
          'Contains date of valuation and date of inspection',
          'May include comparable evidence or market analysis sections',
          'CRITICAL: If RICS branding is present AND formal valuation methodology is used, this is likely a RedBook Valuation even if "RedBook" is not explicitly mentioned',
        ],
        categoryRules:
          'RedBook valuations are professional property appraisals prepared to RICS standards and should ALWAYS be categorized under "Appraisals". They are distinct from informal valuations, broker opinions, or automated valuation models.',
      },
      {
        fileType: 'Cashflow',
        category: 'Appraisals',
        keywords: [
          'cashflow',
          'cash flow',
          'cashflow projection',
          'cash flow analysis',
          'discounted cash flow',
          'dcf',
          'projected cashflow',
          'rental income projection',
          'income projection',
          'net operating income',
          'noi',
          'yield analysis',
          'investment cashflow',
        ],
        description:
          'Cashflow documents are financial projections showing expected income and expenses for a property or development project over time. These documents are critical for development finance as they demonstrate the financial viability of a project and expected returns. Cashflows typically include projected rental income, operating expenses, debt service, and net cash flows over multiple periods. They may be part of an appraisal or standalone financial analysis. Cashflows are used to calculate investment returns, determine loan serviceability, and assess project viability. They often include assumptions about occupancy rates, rental growth, expense inflation, and capital expenditure. Cashflows may be prepared by appraisers as part of income approach valuations or by developers and financial analysts for project planning. They are essential documents for investment decisions and lending approvals.',
        identificationRules: [
          'Look for "Cashflow", "Cash Flow", or "DCF" in the document title or content',
          'Contains projected income and expense figures over multiple periods',
          'Includes rental income projections or revenue forecasts',
          'May include operating expenses, debt service, and net cash flow calculations',
          'Often presented in tabular format showing years or periods',
          'May include assumptions section detailing growth rates, vacancy, and inflation',
          'Could be part of an appraisal document or standalone analysis',
          'May reference NPV (Net Present Value) or IRR (Internal Rate of Return)',
        ],
        categoryRules:
          'Cashflow documents should be categorized under "Appraisals" as they are typically associated with property valuation and investment analysis.',
      },

      // ==========================================
      // PLANS CATEGORY
      // ==========================================
      {
        fileType: 'Floor Plans',
        category: 'Plans',
        keywords: [
          'floor plan',
          'floor plans',
          'floorplan',
          'ground floor',
          'first floor',
          'second floor',
          'basement',
          'layout',
          'room layout',
          'internal layout',
          'accommodation',
          'square footage',
          'sqm',
          'sq ft',
          'gifa',
          'gia',
          'nia',
        ],
        description:
          'Floor Plans are architectural drawings showing the horizontal layout of a building at a specific level. They display the arrangement of rooms, walls, doors, windows, and other features from a bird\'s eye view. Floor plans are essential documents for understanding property configuration and are used in development, sales, and lending. They typically show room dimensions, door and window positions, stairs, and circulation spaces. Floor plans may include annotations for room names, areas, and key features. They are drawn to scale and often include a scale bar and north point. Floor plans are used to calculate Gross Internal Floor Area (GIFA), Net Internal Area (NIA), and other measurements. They are distinct from elevations (vertical views) and sections (cut-through views) as they show horizontal layouts.',
        identificationRules: [
          'Look for "Floor Plan" or specific floor references (Ground Floor, First Floor, etc.)',
          'Shows horizontal layout of building with rooms, walls, doors, and windows',
          'Typically viewed from above (bird\'s eye view)',
          'Includes room names and/or dimensions',
          'May show furniture layouts or fixed fixtures',
          'Contains scale information (e.g., 1:100, 1:50)',
          'Often includes north point for orientation',
          'May include area calculations (sqm, sq ft, GIFA, NIA)',
          'Distinct from elevations and sections - shows horizontal not vertical views',
        ],
        categoryRules:
          'Floor Plans should be categorized under "Plans" as they are architectural drawings. Use this specific type rather than generic "Plans" when the document is clearly a floor plan.',
      },
      {
        fileType: 'Elevations',
        category: 'Plans',
        keywords: [
          'elevation',
          'elevations',
          'front elevation',
          'rear elevation',
          'side elevation',
          'north elevation',
          'south elevation',
          'east elevation',
          'west elevation',
          'street elevation',
          'facade',
          'external view',
          'building exterior',
        ],
        description:
          'Elevations are architectural drawings showing the external vertical faces of a building. They display the exterior appearance including windows, doors, roof lines, and external materials from a straight-on view. Elevations are essential for understanding building design, planning applications, and construction. They typically show front, rear, and side views of a building, often labeled by compass direction (North, South, East, West). Elevations include details of external finishes, window and door styles, roof pitch, and overall building height. They are drawn to scale and may include dimension annotations. Elevations are used in planning submissions to show how a building will appear and in construction to detail external finishes. They are distinct from floor plans (horizontal views) and sections (cut-through views).',
        identificationRules: [
          'Look for "Elevation" in the title or references to compass directions (North, South, East, West)',
          'Shows external vertical view of building facade',
          'Displays windows, doors, roof line, and external features',
          'Viewed straight-on (not from above or in section)',
          'May include height dimensions and floor levels',
          'Often shows material annotations or hatch patterns',
          'Contains scale information',
          'May show multiple elevations on one sheet',
          'Distinct from floor plans and sections',
        ],
        categoryRules:
          'Elevations should be categorized under "Plans" as they are architectural drawings. Use this specific type rather than generic "Plans" when the document clearly shows building elevations.',
      },
      {
        fileType: 'Sections',
        category: 'Plans',
        keywords: [
          'section',
          'sections',
          'cross section',
          'longitudinal section',
          'building section',
          'sectional drawing',
          'cut through',
          'section a-a',
          'section b-b',
          'internal heights',
          'ceiling heights',
        ],
        description:
          'Sections are architectural drawings showing a building as if it has been cut through vertically, revealing internal structure and heights. They display floor-to-ceiling heights, stair configurations, roof structures, and the relationship between different levels. Sections are essential for understanding vertical organization of buildings and are used in construction and planning. They typically show structural elements, internal walls, floor constructions, and roof details. Sections are labeled with reference lines (A-A, B-B, etc.) that correspond to cut lines shown on floor plans. They include dimension annotations for heights and may show material specifications. Sections are distinct from floor plans (horizontal views) and elevations (external vertical views) as they show internal vertical organization.',
        identificationRules: [
          'Look for "Section" in the title, often with reference letters (Section A-A, Section B-B)',
          'Shows building cut through vertically revealing internal structure',
          'Displays floor-to-ceiling heights and internal relationships',
          'Shows stairs, roof structure, and floor construction',
          'Reference line corresponds to cut line on floor plan',
          'Includes height dimensions',
          'May show foundation and below-ground elements',
          'Contains scale information',
          'Distinct from floor plans and elevations - shows internal vertical cut-through',
        ],
        categoryRules:
          'Sections should be categorized under "Plans" as they are architectural drawings. Use this specific type rather than generic "Plans" when the document clearly shows building sections.',
      },
      {
        fileType: 'Site Plans',
        category: 'Plans',
        keywords: [
          'site plan',
          'site plans',
          'site layout',
          'block plan',
          'plot plan',
          'site boundary',
          'red line boundary',
          'blue line boundary',
          'parking layout',
          'landscaping',
          'access road',
          'site entrance',
        ],
        description:
          'Site Plans are drawings showing the arrangement of buildings and features on a piece of land. They display the relationship between buildings, roads, parking, landscaping, and boundaries. Site plans are essential for planning applications, construction, and understanding property context. They typically show building footprints, access roads, parking areas, landscaping, boundaries (often with red line for application site and blue line for ownership), and surrounding context. Site plans are drawn to scale and may include north points, key dimensions, and area calculations. They show how a development fits within its plot and relates to neighboring properties and roads. Site plans are distinct from location plans (which show wider geographic context) and floor plans (which show internal layouts).',
        identificationRules: [
          'Look for "Site Plan", "Site Layout", or "Block Plan" in the title',
          'Shows building footprint(s) within a plot or site',
          'Displays site boundaries, often with red or blue line demarcation',
          'Includes access roads, driveways, and parking areas',
          'May show landscaping, trees, and external features',
          'Shows relationship to neighboring properties',
          'Contains scale and north point',
          'May include area schedules for buildings and open space',
          'Distinct from location plans (wider area) and floor plans (internal)',
        ],
        categoryRules:
          'Site Plans should be categorized under "Plans" as they are technical site drawings. Use this specific type rather than generic "Plans" when the document shows site layout.',
      },
      {
        fileType: 'Location Plans',
        category: 'Plans',
        keywords: [
          'location plan',
          'location plans',
          'site location',
          'ordnance survey',
          'os map',
          '1:1250',
          '1:2500',
          'wider context',
          'surrounding area',
          'map extract',
          'area map',
        ],
        description:
          'Location Plans are maps showing the wider geographic context of a property or development site. They display the site in relation to surrounding roads, buildings, and landmarks, typically at scales of 1:1250 or 1:2500. Location plans are required for planning applications and help identify the property location. They typically use Ordnance Survey base mapping with the application site outlined in red. Location plans show surrounding streets, neighboring buildings, and key features that help locate the property. They include north points, scale bars, and often street names. Location plans are distinct from site plans (which show detailed site layout) as they provide wider geographic context rather than detailed site information.',
        identificationRules: [
          'Look for "Location Plan" or "Site Location Plan" in the title',
          'Shows wider geographic area around the site',
          'Typically uses Ordnance Survey or similar base mapping',
          'Site often outlined in red',
          'Scale typically 1:1250 or 1:2500',
          'Shows surrounding roads, buildings, and landmarks',
          'Includes street names and key features for identification',
          'Contains north point and scale bar',
          'Distinct from site plans - shows wider area context',
        ],
        categoryRules:
          'Location Plans should be categorized under "Plans" as they are technical planning drawings. Use this specific type rather than generic "Plans" when the document shows wider location context.',
      },

      // ==========================================
      // INSPECTIONS / PROFESSIONAL REPORTS CATEGORY
      // ==========================================
      {
        fileType: 'Initial Monitoring Report',
        category: 'Inspections',
        keywords: [
          'initial monitoring report',
          'initial monitoring',
          'initial report',
          'monitoring surveyor',
          'lender monitoring',
          'monitoring surveyor initial',
          'pre-funding monitoring',
          'due diligence monitoring',
          'pre-construction monitoring',
          'monitoring report initial',
          'construction cost estimate',
          'build cost estimate',
          'construction timeline',
          'build programme',
          'project cost estimate',
        ],
        description:
          'Initial Monitoring Reports are formal due diligence reports prepared before a project is funded. They assess construction costs, timelines, and project viability to inform funding decisions. These reports are typically one-time assessments done at the project inception stage. They contain construction cost estimates or build cost breakdowns, project timelines or build programmes showing how long construction will take, and are prepared as part of formal due diligence process before funding. Initial Monitoring Reports may reference pre-funding, pre-construction, or due diligence context and typically include cost analysis, timeline assessment, and project viability evaluation. They may include site conditions assessment and construction methodology review and are often prepared by quantity surveyors, project managers, or construction consultants. The document date should be early in project lifecycle before construction starts or very early stages. Initial Monitoring Reports are distinct from Interim Monitoring Reports which are ongoing monthly progress reports, not one-time pre-funding assessments.',
        identificationRules: [
          'Look for "Initial Monitoring Report" or "Initial Monitoring" in the document title or header',
          'Contains construction cost estimates or build cost breakdowns',
          'Includes project timeline or build programme (how long construction will take)',
          'Prepared as part of formal due diligence process before funding',
          'May reference "pre-funding", "pre-construction", or "due diligence" context',
          'Typically includes cost analysis, timeline assessment, and project viability evaluation',
          'May include site conditions assessment and construction methodology review',
          'Often prepared by quantity surveyors, project managers, or construction consultants',
          'Document date should be early in project lifecycle (before construction starts or very early stages)',
          'Distinguish from Interim Monitoring Reports: Initial reports are one-time pre-funding assessments, not monthly progress reports',
        ],
        categoryRules:
          'Initial Monitoring Reports are inspection/monitoring documents prepared during due diligence and should be categorized under "Inspections". They are distinct from Interim Monitoring Reports which are ongoing monthly reports.',
      },
      {
        fileType: 'Interim Monitoring Report',
        category: 'Inspections',
        keywords: [
          'interim monitoring report',
          'interim monitoring',
          'monthly monitoring report',
          'monthly monitoring',
          'progress monitoring report',
          'construction progress report',
          'funding drawdown report',
          'drawdown monitoring',
          'monthly sign-off',
          'construction sign-off',
        ],
        description:
          'Interim Monitoring Reports are monthly progress reports prepared during construction to sign off on funding for additional construction works. These are ongoing reports that track project progress, verify completed work, and authorize further funding releases. They may include Monthly in the title and contain progress updates on construction work completed since last report. Interim Monitoring Reports include verification of completed work and quality assessment and authorize or recommend funding release for next phase of construction. They are prepared monthly or at regular intervals during construction and may reference previous monitoring reports or report numbers. These reports include percentage completion or milestone tracking and may include photographs or evidence of completed work. The document date should be during active construction phase. Interim Monitoring Reports are distinct from Initial Monitoring Reports which are one-time pre-funding due diligence reports, not ongoing monthly assessments during construction.',
        identificationRules: [
          'Look for "Interim Monitoring Report" or "Interim Monitoring" in the document title or header',
          'May include "Monthly" in the title (e.g., "Monthly Interim Monitoring Report")',
          'Contains progress updates on construction work completed since last report',
          'Includes verification of completed work and quality assessment',
          'Authorizes or recommends funding release for next phase of construction',
          'Prepared monthly or at regular intervals during construction',
          'May reference previous monitoring reports or report numbers (e.g., "Report #3", "Month 3")',
          'Includes percentage completion or milestone tracking',
          'May include photographs or evidence of completed work',
          'Document date should be during active construction phase',
          'Distinguish from Initial Monitoring Reports: Interim reports are ongoing monthly assessments during construction, not one-time pre-funding reports',
        ],
        categoryRules:
          'Interim Monitoring Reports are inspection/monitoring documents prepared during construction to authorize funding releases and should be categorized under "Inspections". They are distinct from Initial Monitoring Reports which are one-time pre-funding due diligence reports.',
      },
      {
        fileType: 'Planning Documentation',
        category: 'Professional Reports',
        keywords: [
          'planning permission',
          'planning approval',
          'planning decision',
          'planning consent',
          'planning application',
          'decision notice',
          'planning notice',
          'permitted development',
          'planning conditions',
          'section 106',
          's106',
          'cil',
          'community infrastructure levy',
          'planning reference',
          'local planning authority',
          'lpa',
        ],
        description:
          'Planning Documentation includes official documents related to planning permissions, approvals, and applications for development projects. These documents are issued by Local Planning Authorities and confirm whether development can proceed. Planning documents include decision notices that grant or refuse permission, planning application forms and supporting documents, and any conditions attached to approvals. They may include Section 106 agreements or Community Infrastructure Levy (CIL) requirements. Planning documentation is essential for development finance as it confirms the legal basis for construction. It includes planning reference numbers, site addresses, descriptions of approved development, and any specific conditions that must be met. Planning documents are formal legal documents that determine what can be built on a site.',
        identificationRules: [
          'Look for "Planning Permission", "Decision Notice", or "Planning Approval" in the title',
          'Contains planning reference numbers (e.g., "Planning Ref: 2023/1234")',
          'Issued by a Local Planning Authority (Council)',
          'Includes site address and description of approved development',
          'May list conditions attached to the permission',
          'Contains decision date and approval status',
          'May reference Section 106 agreements or CIL',
          'Often includes plans approved as part of the permission',
          'Contains official council letterhead or stamps',
        ],
        categoryRules:
          'Planning Documentation should be categorized under "Professional Reports" as these are official documents confirming development approvals.',
      },
      {
        fileType: 'Contract Sum Analysis',
        category: 'Professional Reports',
        keywords: [
          'contract sum analysis',
          'csa',
          'cost plan',
          'budget',
          'construction budget',
          'build cost',
          'elemental cost plan',
          'cost breakdown',
          'bill of quantities',
          'boq',
          'tender analysis',
          'construction costs',
          'preliminaries',
          'contingency',
        ],
        description:
          'Contract Sum Analysis (CSA) documents provide detailed breakdowns of construction costs for development projects. Also known as Cost Plans or Budgets, these documents itemize all costs associated with building works. They are prepared by quantity surveyors or cost consultants and are essential for development finance appraisals. Contract Sum Analysis typically breaks down costs by building element (substructure, superstructure, finishes, services, etc.) or by trade (groundworks, brickwork, roofing, electrical, plumbing, etc.). They include preliminaries (site setup, management), contingencies for unforeseen costs, and professional fees. These documents are used to verify the reasonableness of construction costs and monitor spending during construction. They may be initial budgets or analysis of received tenders.',
        identificationRules: [
          'Look for "Contract Sum Analysis", "Cost Plan", or "Budget" in the title',
          'Contains itemized breakdown of construction costs',
          'May be organized by building element or trade',
          'Includes preliminaries, contingency, and professional fees',
          'Often prepared by quantity surveyors or cost consultants',
          'Shows total construction cost or contract sum',
          'May include cost per square meter/foot comparisons',
          'Could be budget estimate or tender analysis',
          'Contains detailed line items with quantities and rates',
        ],
        categoryRules:
          'Contract Sum Analysis documents should be categorized under "Professional Reports" as they are formal cost assessments prepared by professionals.',
      },
      {
        fileType: 'Comparables',
        category: 'Professional Reports',
        keywords: [
          'comparables',
          'comps',
          'comparable evidence',
          'rental comparables',
          'sales comparables',
          'comparable transactions',
          'market evidence',
          'comparable properties',
          'rent comparables',
          'asking rents',
          'achieved rents',
          'sale prices',
          'transaction evidence',
        ],
        description:
          'Comparables documents provide market evidence of rental values or sales prices for similar properties in an area. They are used to support valuations, rental assessments, and investment decisions. Rental comparables show achieved or asking rents for similar properties, while sales comparables show transaction prices. Comparables typically include property addresses, sizes, dates of transaction or lease, and key features for comparison. They may be schedules prepared by valuers, agent particulars, or market research reports. Comparables are essential for validating assumptions in appraisals and cashflows. They help establish market rates and demonstrate demand for a particular property type or location. Comparables may be presented as tables, individual property details, or market analysis reports.',
        identificationRules: [
          'Look for "Comparables", "Comparable Evidence", or "Market Evidence" in the title or content',
          'Contains data on similar properties used for comparison',
          'Includes property addresses, sizes, and values (rent or price)',
          'Shows transaction or lease dates',
          'May include photos or details of comparable properties',
          'Often presented in tabular format',
          'Distinguishes between asking and achieved values',
          'May be part of an appraisal or standalone document',
          'Contains analysis of how comparables relate to subject property',
        ],
        categoryRules:
          'Comparables documents should be categorized under "Professional Reports" as they are market research supporting professional valuations.',
      },

      // ==========================================
      // KYC CATEGORY
      // ==========================================
      {
        fileType: 'Passport',
        category: 'KYC',
        keywords: [
          'passport',
          'travel document',
          'identity document',
          'id document',
          'passport number',
          'nationality',
          'date of birth',
          'place of birth',
          'mrz',
          'machine readable zone',
          'biometric passport',
        ],
        description:
          'Passports are official government-issued identity documents used for international travel and personal identification. They contain the holder\'s photograph, full name, date of birth, nationality, and unique passport number. Passports are primary documents for Know Your Customer (KYC) verification in financial services. They include machine-readable zones (MRZ) with encoded personal information and security features such as holograms, watermarks, and biometric data. Passports are issued by national governments and have expiry dates. For KYC purposes, passports must typically be valid (not expired) and clearly legible. Certified copies may be required for some purposes. Passports confirm identity and nationality for anti-money laundering compliance.',
        identificationRules: [
          'Look for passport booklet format or photo page scan',
          'Contains photograph of the holder',
          'Shows full name, date of birth, and nationality',
          'Includes passport number and expiry date',
          'Has machine-readable zone (MRZ) at bottom of data page',
          'Shows issuing country and government insignia',
          'May include signature of holder',
          'Contains security features (holograms, watermarks)',
          'Government-issued official document',
        ],
        categoryRules:
          'Passports should be categorized under "KYC" as they are primary identity documents used for customer verification.',
      },
      {
        fileType: 'Driving License',
        category: 'KYC',
        keywords: [
          'driving licence',
          'driving license',
          'driver licence',
          'driver license',
          'dvla',
          'licence number',
          'license number',
          'provisional licence',
          'full licence',
          'photo card',
          'counterpart',
          'vehicle categories',
        ],
        description:
          'Driving Licenses are government-issued documents authorizing individuals to operate motor vehicles. They serve as photo identification documents for Know Your Customer (KYC) verification. Driving licenses contain the holder\'s photograph, full name, date of birth, address, and unique license number. In the UK, they are issued by the DVLA (Driver and Vehicle Licensing Agency). They include vehicle categories the holder is permitted to drive and may show endorsements or restrictions. Driving licenses have photo card and previously paper counterpart components. They are widely accepted as proof of identity and address for KYC purposes. Driving licenses must typically be valid and clearly legible for verification.',
        identificationRules: [
          'Look for driving licence/license format (card or paper)',
          'Contains photograph of the holder',
          'Shows full name, date of birth, and address',
          'Includes licence/license number',
          'Shows vehicle categories (A, B, C, etc.)',
          'May show DVLA or equivalent authority branding',
          'Contains issue and expiry dates',
          'May include provisional or full licence status',
          'Government-issued official document',
        ],
        categoryRules:
          'Driving Licenses should be categorized under "KYC" as they are primary identity documents used for customer verification.',
      },
      {
        fileType: 'Utility Bill',
        category: 'KYC',
        keywords: [
          'utility bill',
          'electricity bill',
          'gas bill',
          'water bill',
          'council tax',
          'phone bill',
          'broadband bill',
          'energy bill',
          'account statement',
          'proof of address',
          'residential address',
        ],
        description:
          'Utility Bills are periodic statements from utility providers showing charges for services such as electricity, gas, water, telephone, or broadband. They are commonly used as proof of address for Know Your Customer (KYC) verification. Utility bills contain the customer\'s name and residential address, account number, billing period, and amount due or paid. They are issued by utility companies and local councils (for council tax). For KYC purposes, utility bills must typically be recent (within 3 months), show the customer\'s current address, and be from an acceptable provider. Digital bills or online statements are often accepted alongside paper bills. Utility bills confirm residential address for anti-money laundering compliance.',
        identificationRules: [
          'Look for utility provider branding (energy, water, telecom company)',
          'Contains customer name and residential address',
          'Shows account number or reference',
          'Includes billing period and date',
          'Shows charges, amounts due, or payments',
          'May include meter readings or usage data',
          'Issued by utility provider or local council',
          'Should be recent (typically within 3 months for KYC)',
          'Contains provider contact details',
        ],
        categoryRules:
          'Utility Bills should be categorized under "KYC" as they are proof of address documents used for customer verification.',
      },
      {
        fileType: 'Bank Statement',
        category: 'KYC',
        keywords: [
          'bank statement',
          'account statement',
          'current account',
          'savings account',
          'transaction history',
          'bank account',
          'account balance',
          'statement period',
          'monthly statement',
          'sort code',
          'account number',
        ],
        description:
          'Bank Statements are periodic documents from financial institutions showing account activity, transactions, and balances. They are used for Know Your Customer (KYC) verification as proof of address and for financial due diligence. Bank statements contain the account holder\'s name and address, account number, sort code, and transaction history for the statement period. They show deposits, withdrawals, payments, and running balances. Bank statements can verify identity, address, and financial position. For KYC purposes, statements must typically be recent (within 3 months) and from a regulated financial institution. Personal and business bank statements may be required for different purposes in development finance.',
        identificationRules: [
          'Look for bank or building society branding',
          'Contains account holder name and address',
          'Shows account number and sort code',
          'Includes statement period dates',
          'Lists individual transactions with dates and amounts',
          'Shows opening and closing balances',
          'May include interest earned or charges',
          'Issued by regulated financial institution',
          'Should be recent for KYC purposes (typically within 3 months)',
        ],
        categoryRules:
          'Bank Statements should be categorized under "KYC" as they are proof of address and financial verification documents.',
      },
      {
        fileType: 'Application Form',
        category: 'KYC',
        keywords: [
          'application form',
          'loan application',
          'finance application',
          'credit application',
          'customer application',
          'borrower application',
          'personal details',
          'company details',
          'application submission',
          'kyc form',
        ],
        description:
          'Application Forms are structured documents used to collect information from customers applying for finance or services. They capture personal and business details required for Know Your Customer (KYC) compliance and credit assessment. Application forms typically request contact details, identification information, financial details, employment or business information, and declarations. They may be paper forms, PDFs, or online submissions. Application forms establish the customer relationship and document consent for processing. They are the starting point for due diligence and capture information that will be verified through supporting documents. Application forms vary by lender but generally collect standardized KYC information required by regulations.',
        identificationRules: [
          'Look for "Application Form" or similar title',
          'Contains structured fields for personal or business information',
          'Requests name, address, contact details, and identification numbers',
          'May include financial information sections',
          'Contains declarations and signature sections',
          'Often has multiple pages or sections',
          'May be branded by the lender or company',
          'Includes date fields and reference numbers',
          'Structured format with checkboxes, fields, and sections',
        ],
        categoryRules:
          'Application Forms should be categorized under "KYC" as they are the primary customer data collection documents.',
      },
      {
        fileType: 'Assets & Liabilities Statement',
        category: 'KYC',
        keywords: [
          'assets and liabilities',
          'assets & liabilities',
          'personal assets',
          'net worth',
          'statement of affairs',
          'personal balance sheet',
          'property portfolio',
          'investment portfolio',
          'debts',
          'mortgages',
          'loans outstanding',
          'financial position',
        ],
        description:
          'Assets & Liabilities Statements are personal financial statements showing an individual\'s or company\'s financial position. They list assets (property, investments, cash, other valuables) and liabilities (mortgages, loans, debts) to calculate net worth. These statements are required for Know Your Customer (KYC) due diligence and credit assessment in development finance. They help lenders understand the borrower\'s overall financial strength and obligations. Assets & Liabilities Statements typically include property values, investment portfolios, bank balances, vehicle values, and other significant assets. Liabilities include mortgages, loans, credit cards, and other debts. The net position (assets minus liabilities) indicates financial strength. These may be self-declared or prepared by accountants.',
        identificationRules: [
          'Look for "Assets & Liabilities", "Statement of Affairs", or "Net Worth Statement" in title',
          'Lists assets with values (property, investments, cash, etc.)',
          'Lists liabilities with amounts (mortgages, loans, debts)',
          'Shows total assets and total liabilities',
          'Calculates net worth or net position',
          'May include property addresses and valuations',
          'Often includes a date or "as at" reference',
          'May be self-declared or accountant-prepared',
          'Contains signature or certification',
        ],
        categoryRules:
          'Assets & Liabilities Statements should be categorized under "KYC" as they are financial due diligence documents.',
      },

      // ==========================================
      // LOAN TERMS CATEGORY
      // ==========================================
      {
        fileType: 'Indicative Terms',
        category: 'Loan Terms',
        keywords: [
          'indicative terms',
          'indicative term',
          'heads of terms',
          'development finance',
          'development finance deal',
          'development loan',
          'bridging loan',
          'bridging finance',
          'loan terms',
          'finance terms',
          'loan facility',
          'facility terms',
          'ltgdv',
          'lgdv',
          'loan to gdv',
          'loan to gross development value',
          'land loan',
          'land advance',
          'arrangement fee',
          'broker fee',
          'exit fee',
          'in principle',
          'indicative pricing',
        ],
        description:
          'Indicative Terms (also known as Heads of Terms) are preliminary loan offers for development finance deals. These documents outline proposed loan terms including facility amounts, interest rates, fees (arrangement fees, broker fees, exit fees), loan structure breakdowns (land advance, build costs, professional fees, contingency), loan-to-value ratios (LTGDV, LGDV), and terms. These are typically in principle offers subject to further due diligence and Credit Committee approval. Indicative Terms contain development finance or bridging loan terminology and include loan facility amounts and terms. They contain interest rate information expressed as percentages per annum plus base rate or all-in rates. They are preliminary and non-binding, setting out the basis on which a lender would consider providing finance. Indicative Terms are distinct from formal loan agreements as they are preliminary offers, not final binding agreements.',
        identificationRules: [
          'Look for "Indicative Terms", "Heads of Terms", or "Term Sheet" in the document title or header',
          'Contains development finance or bridging loan terminology',
          'Includes loan facility amounts and terms (e.g., "£2,503,000 over 17 months")',
          'Contains interest rate information (e.g., "5.25% per annum plus BBR")',
          'Includes fee breakdowns: arrangement fees, broker fees, exit fees',
          'Contains loan structure breakdown: Land advance, Build costs, Contingency',
          'May reference loan-to-value ratios: LTGDV, LGDV',
          'Often states "in principle", "subject to further due diligence"',
          'Contains non-binding language indicating preliminary nature',
          'Distinguish from formal loan agreements: These are preliminary offers',
        ],
        categoryRules:
          'Indicative Terms should be categorized under "Loan Terms" as they are preliminary loan offers. They are distinct from formal loan agreements or facility letters.',
      },
      {
        fileType: 'Credit Backed Terms',
        category: 'Loan Terms',
        keywords: [
          'credit backed terms',
          'credit approved terms',
          'credit committee approved',
          'approved terms',
          'credit approved',
          'formal terms',
          'binding terms',
          'committed terms',
          'credit sanctioned',
          'approved facility',
        ],
        description:
          'Credit Backed Terms are loan terms that have received formal credit committee approval, moving beyond indicative offers to committed terms. These documents confirm that a lender\'s credit committee has approved the proposed transaction subject to specific conditions. Credit Backed Terms represent a more advanced stage in the lending process than Indicative Terms, indicating genuine lender commitment. They typically include all the same information as Indicative Terms (facility amount, rates, fees, structure) but with credit committee endorsement. Credit Backed Terms are still subject to legal documentation and any conditions precedent, but represent a formal commitment from the lender. They provide borrowers with greater certainty that funding will be available.',
        identificationRules: [
          'Look for "Credit Backed", "Credit Approved", or "Committed Terms" in the title',
          'Contains statement of credit committee approval',
          'Includes specific facility amounts, rates, and fees',
          'May reference credit committee date or reference number',
          'Contains conditions precedent to drawdown',
          'More formal language than indicative terms',
          'May include validity period for the approval',
          'Often includes more detailed terms than indicative offers',
          'Represents lender commitment subject to documentation',
        ],
        categoryRules:
          'Credit Backed Terms should be categorized under "Loan Terms" as they are approved loan terms. They are more advanced than Indicative Terms but precede formal loan agreements.',
      },

      // ==========================================
      // LEGAL DOCUMENTS CATEGORY
      // ==========================================
      {
        fileType: 'Facility Letter',
        category: 'Legal Documents',
        keywords: [
          'facility letter',
          'facility agreement',
          'loan agreement',
          'credit agreement',
          'lending agreement',
          'finance agreement',
          'loan facility',
          'credit facility',
          'term loan',
          'revolving facility',
          'drawdown',
          'repayment schedule',
        ],
        description:
          'Facility Letters (also known as Loan Agreements) are the formal legal documents that establish the terms and conditions of a loan between lender and borrower. They are binding contracts that set out the loan amount, interest rate, fees, repayment terms, covenants, representations, and events of default. Facility Letters are prepared by legal professionals and require execution by all parties. They typically include definitions, conditions precedent to drawdown, representations and warranties, covenants (financial and general), events of default, and remedies. Facility Letters may include schedules with property details, drawdown mechanics, and security requirements. They are the definitive legal record of the lending arrangement and supersede any earlier indicative or credit-backed terms.',
        identificationRules: [
          'Look for "Facility Letter", "Loan Agreement", or "Credit Agreement" in the title',
          'Contains formal legal language and structure',
          'Includes defined terms section',
          'Sets out loan amount, interest rate, and fees',
          'Contains conditions precedent to first drawdown',
          'Includes representations, warranties, and covenants',
          'Lists events of default and remedies',
          'Contains execution blocks for signatures',
          'Prepared by solicitors or legal counsel',
          'Multiple pages with schedules and annexes',
        ],
        categoryRules:
          'Facility Letters should be categorized under "Legal Documents" as they are formal binding loan agreements.',
      },
      {
        fileType: 'Personal Guarantee',
        category: 'Legal Documents',
        keywords: [
          'personal guarantee',
          'pg',
          'guarantor',
          'guarantee',
          'personal guarantor',
          'joint and several',
          'unlimited guarantee',
          'limited guarantee',
          'director guarantee',
          'individual guarantee',
        ],
        description:
          'Personal Guarantees are legal documents where an individual agrees to be personally responsible for a borrower\'s obligations if they default. They are common in development finance where company borrowers require directors or shareholders to provide personal backing. Personal Guarantees may be unlimited (covering all obligations) or limited to a specific amount. They typically contain the guarantor\'s undertaking, the extent of liability, conditions for enforcement, and provisions for the guarantee to continue despite changes to the underlying facility. Personal Guarantees are serious legal commitments that can result in personal liability including against personal assets. They are executed as deeds and require independent legal advice certificates.',
        identificationRules: [
          'Look for "Personal Guarantee" or "Guarantee" in the title',
          'Names individual guarantor(s)',
          'References the underlying loan or facility being guaranteed',
          'Contains guarantee undertaking language',
          'May specify guarantee limit or state unlimited',
          'Includes provisions for enforcement',
          'Often requires independent legal advice certificate',
          'Executed as a deed with witness',
          'Contains provisions for continuing guarantee',
        ],
        categoryRules:
          'Personal Guarantees should be categorized under "Legal Documents" as they are formal security documents.',
      },
      {
        fileType: 'Corporate Guarantee',
        category: 'Legal Documents',
        keywords: [
          'corporate guarantee',
          'company guarantee',
          'group guarantee',
          'parent company guarantee',
          'subsidiary guarantee',
          'cross guarantee',
          'corporate guarantor',
        ],
        description:
          'Corporate Guarantees are legal documents where a company agrees to be responsible for another entity\'s obligations. They are used in development finance where group companies provide backing for borrowing entities. Corporate Guarantees may be given by parent companies for subsidiaries, by holding companies, or as cross-guarantees between group entities. They typically contain the guarantor company\'s undertaking, board authorization, the extent of liability, conditions for enforcement, and provisions regarding the corporate guarantor\'s ongoing obligations. Corporate Guarantees provide lenders with additional security by having financially stronger group entities back the borrower. They require proper corporate authorization through board resolutions.',
        identificationRules: [
          'Look for "Corporate Guarantee" or "Company Guarantee" in the title',
          'Names corporate guarantor (company, not individual)',
          'References the underlying loan or facility being guaranteed',
          'Contains corporate guarantee undertaking',
          'May include reference to board authorization',
          'Contains provisions regarding guarantor\'s obligations',
          'Often accompanied by board resolution or corporate authorization',
          'Executed with company seal or authorized signatories',
        ],
        categoryRules:
          'Corporate Guarantees should be categorized under "Legal Documents" as they are formal corporate security documents.',
      },
      {
        fileType: 'Terms & Conditions',
        category: 'Legal Documents',
        keywords: [
          'terms and conditions',
          'terms & conditions',
          't&c',
          'standard terms',
          'general conditions',
          'conditions of business',
          'terms of business',
          'standard conditions',
        ],
        description:
          'Terms & Conditions are standard legal documents setting out the rules and requirements that apply to a business relationship or service. In development finance, they may be attached to facility letters or issued separately to govern the lending relationship. Terms & Conditions typically include definitions, general provisions, payment terms, liability limitations, governing law, and dispute resolution procedures. They are pre-drafted documents that apply across multiple transactions, distinguishing them from transaction-specific agreements. Terms & Conditions should be read alongside facility-specific documents. They establish baseline rules while specific facility letters set out transaction-specific terms.',
        identificationRules: [
          'Look for "Terms & Conditions" or "General Conditions" in the title',
          'Contains standardized legal provisions',
          'Includes definitions and interpretation clauses',
          'Sets out general obligations and rights',
          'Contains limitation of liability clauses',
          'Includes governing law and jurisdiction',
          'May contain dispute resolution procedures',
          'Pre-drafted standard document (not transaction-specific)',
          'Often referenced by or attached to other agreements',
        ],
        categoryRules:
          'Terms & Conditions should be categorized under "Legal Documents" as they are standard legal documents.',
      },
      {
        fileType: 'Shareholders Agreement',
        category: 'Legal Documents',
        keywords: [
          'shareholders agreement',
          'shareholder agreement',
          'sha',
          'shareholders\' agreement',
          'joint venture agreement',
          'jv agreement',
          'voting rights',
          'share transfer',
          'pre-emption',
          'drag along',
          'tag along',
          'deadlock',
        ],
        description:
          'Shareholders Agreements are legal contracts between shareholders of a company setting out how the company will be operated and shareholders\' rights. They supplement the company\'s articles of association with additional private arrangements. Shareholders Agreements typically cover decision-making procedures, voting rights, dividend policies, share transfer restrictions (pre-emption rights, drag-along, tag-along), deadlock resolution, and exit mechanisms. In development finance, they are relevant when multiple parties invest in a development company (SPV). Lenders review shareholders agreements to understand company control, restrictions on share transfers, and any provisions that might affect security enforcement.',
        identificationRules: [
          'Look for "Shareholders Agreement" or "JV Agreement" in the title',
          'Names the company and its shareholders',
          'Contains provisions about company governance',
          'Includes voting rights and decision-making procedures',
          'Sets out share transfer restrictions (pre-emption, etc.)',
          'May include drag-along and tag-along provisions',
          'Contains deadlock resolution mechanisms',
          'Executed by all shareholders',
          'Often confidential to the parties',
        ],
        categoryRules:
          'Shareholders Agreements should be categorized under "Legal Documents" as they are corporate governance agreements.',
      },
      {
        fileType: 'Share Charge',
        category: 'Legal Documents',
        keywords: [
          'share charge',
          'charge over shares',
          'share security',
          'equity pledge',
          'share pledge',
          'shares as security',
          'charged shares',
          'share certificate',
          'stock transfer form',
        ],
        description:
          'Share Charges are security documents where shares in a company are pledged as collateral for a loan. They are common in development finance where shares in the borrowing SPV (Special Purpose Vehicle) are charged to the lender. Share Charges give lenders the right to take ownership of shares if the borrower defaults, allowing them to take control of the company and its assets. They typically require deposit of share certificates and signed but undated stock transfer forms. Share Charges include provisions about voting rights during the charge period, restrictions on share dealings, and enforcement mechanisms. They are often registered at Companies House and create a security interest in the shares.',
        identificationRules: [
          'Look for "Share Charge" or "Charge over Shares" in the title',
          'Names the chargor (share owner) and chargee (lender)',
          'Identifies the shares being charged',
          'References share certificates and stock transfer forms',
          'Contains provisions about voting rights',
          'Includes restrictions on share dealings',
          'Sets out enforcement procedures',
          'May be registered at Companies House',
          'Executed as a deed',
        ],
        categoryRules:
          'Share Charges should be categorized under "Legal Documents" as they are security documents over company shares.',
      },
      {
        fileType: 'Debenture',
        category: 'Legal Documents',
        keywords: [
          'debenture',
          'fixed charge',
          'floating charge',
          'fixed and floating charge',
          'all assets charge',
          'security over assets',
          'crystallization',
          'companies house registration',
          'priority',
        ],
        description:
          'Debentures are security documents that create fixed and/or floating charges over a company\'s assets. They are standard security in development finance, giving lenders charges over the borrower\'s undertaking and assets. Fixed charges attach to specific identifiable assets (property, equipment) while floating charges cover changing assets (stock, debtors, cash). Debentures include provisions about restrictions on dealing with charged assets, crystallization of floating charges, and enforcement rights. They must be registered at Companies House within 21 days of creation. Debentures rank behind legal mortgages over property but provide security over other company assets not covered by specific charges.',
        identificationRules: [
          'Look for "Debenture" in the title',
          'Creates fixed and/or floating charges over company assets',
          'Names the company granting security and the secured party',
          'Contains schedules of charged assets',
          'Includes provisions about crystallization of floating charge',
          'Sets out restrictions on dealing with assets',
          'Contains enforcement provisions',
          'Requires registration at Companies House',
          'Executed as a deed by the company',
        ],
        categoryRules:
          'Debentures should be categorized under "Legal Documents" as they are security documents over company assets.',
      },
      {
        fileType: 'Corporate Authorisations',
        category: 'Legal Documents',
        keywords: [
          'board resolution',
          'board minutes',
          'corporate resolution',
          'directors resolution',
          'shareholder resolution',
          'written resolution',
          'authority to sign',
          'signing authority',
          'company authorization',
          'company authorisation',
          'certificate of incumbency',
        ],
        description:
          'Corporate Authorisations are documents evidencing that a company has properly authorized a transaction or the signing of documents. They include board resolutions, shareholder resolutions, and certificates of incumbency. Board resolutions record directors\' decisions to enter into transactions and authorize specific individuals to sign documents on the company\'s behalf. They typically confirm the company has power to enter the transaction, approve the specific transaction, and authorize named individuals to execute documents. Corporate Authorisations are required by lenders to ensure companies have proper authority for transactions. They may need to be certified by company secretary or director.',
        identificationRules: [
          'Look for "Board Resolution", "Resolution", or "Authorization" in the title',
          'Names the company and date of resolution',
          'Confirms company has power for the transaction',
          'Approves the specific transaction or facility',
          'Names authorized signatories',
          'May be minutes of a meeting or written resolution',
          'Signed by chair or company secretary',
          'May include certification of accuracy',
          'Often attached to other transaction documents',
        ],
        categoryRules:
          'Corporate Authorisations should be categorized under "Legal Documents" as they are corporate governance documents.',
      },

      // ==========================================
      // PROJECT DOCUMENTS CATEGORY
      // ==========================================
      {
        fileType: 'Accommodation Schedule',
        category: 'Project Documents',
        keywords: [
          'accommodation schedule',
          'unit schedule',
          'apartment schedule',
          'unit mix',
          'unit breakdown',
          'flat schedule',
          'house schedule',
          'bedroom mix',
          'unit types',
          'sqm schedule',
          'area schedule',
        ],
        description:
          'Accommodation Schedules are documents listing all units in a development with their specifications. They provide a breakdown of unit types, sizes, and configuration for residential or commercial developments. Accommodation Schedules typically show unit numbers, types (1-bed, 2-bed, studio, etc.), floor areas (gross and net), floor levels, and any parking or storage allocations. They are essential for development appraisals, sales projections, and construction planning. Accommodation Schedules allow lenders to verify unit mix against appraisal assumptions and assess scheme viability. They may be prepared by architects, developers, or agents and are often updated as designs evolve.',
        identificationRules: [
          'Look for "Accommodation Schedule" or "Unit Schedule" in the title',
          'Contains list of individual units',
          'Shows unit types (1-bed, 2-bed, studio, etc.)',
          'Includes floor areas for each unit (sqm or sq ft)',
          'May show floor levels and unit positions',
          'Often includes totals (total units, total area)',
          'May include parking and storage allocations',
          'Typically in tabular format',
          'Shows unit mix breakdown',
        ],
        categoryRules:
          'Accommodation Schedules should be categorized under "Project Documents" as they are development planning documents.',
      },
      {
        fileType: 'Build Programme',
        category: 'Project Documents',
        keywords: [
          'build programme',
          'construction programme',
          'project programme',
          'gantt chart',
          'project timeline',
          'construction schedule',
          'work programme',
          'milestone schedule',
          'critical path',
          'project plan',
          'phasing',
        ],
        description:
          'Build Programmes (also called Construction Programmes) are project planning documents showing the timeline for construction works. They illustrate the sequence and duration of construction activities from start to completion. Build Programmes are typically presented as Gantt charts showing tasks, durations, dependencies, and milestones. They include key phases such as groundworks, substructure, superstructure, fit-out, and completion. Build Programmes are essential for monitoring construction progress, coordinating trades, and managing drawdown schedules. Lenders use them to verify project timelines and assess whether construction is progressing as planned. They may be prepared by main contractors, project managers, or developers.',
        identificationRules: [
          'Look for "Build Programme", "Construction Programme", or "Project Programme" in the title',
          'Contains timeline of construction activities',
          'Often presented as Gantt chart format',
          'Shows task names, durations, and dependencies',
          'Includes key milestones and phases',
          'Shows start and end dates',
          'May include critical path analysis',
          'Contains construction activities (groundworks, structure, etc.)',
          'May show resource allocation or responsibilities',
        ],
        categoryRules:
          'Build Programmes should be categorized under "Project Documents" as they are construction planning documents.',
      },

      // ==========================================
      // FINANCIAL DOCUMENTS CATEGORY
      // ==========================================
      {
        fileType: 'Loan Statement',
        category: 'Financial Documents',
        keywords: [
          'loan statement',
          'facility statement',
          'loan account',
          'facility account',
          'loan balance',
          'outstanding balance',
          'interest accrued',
          'drawdown statement',
          'loan position',
        ],
        description:
          'Loan Statements are documents showing the current position of a loan account. They detail the amounts drawn, interest accrued, fees charged, payments made, and outstanding balance. Loan Statements are issued by lenders periodically or on request to confirm the state of the loan. They typically show opening balance, transactions during the period, interest calculations, and closing balance. Loan Statements are important for borrowers to track their obligations and for refinancing purposes where lenders need to understand existing debt. They may include breakdown by facility tranche, interest rate information, and next payment due dates.',
        identificationRules: [
          'Look for "Loan Statement" or "Facility Statement" in the title',
          'Shows outstanding loan balance',
          'Contains transaction history (drawdowns, payments)',
          'Includes interest accrued or charged',
          'Shows opening and closing balances',
          'May include facility limit and available headroom',
          'Contains lender branding',
          'Shows statement date and period',
          'May include interest rate and next payment information',
        ],
        categoryRules:
          'Loan Statements should be categorized under "Financial Documents" as they are loan account records.',
      },
      {
        fileType: 'Redemption Statement',
        category: 'Financial Documents',
        keywords: [
          'redemption statement',
          'redemption figure',
          'payoff statement',
          'settlement figure',
          'early repayment',
          'loan payoff',
          'discharge amount',
          'payout figure',
          'final payment',
        ],
        description:
          'Redemption Statements are documents showing the exact amount required to fully repay and close a loan on a specific date. They are issued by lenders when borrowers want to pay off their loans early or at maturity. Redemption Statements include outstanding principal, accrued interest to the redemption date, any early repayment charges, administration fees, and the total amount required. They typically have a validity period as interest continues to accrue. Redemption Statements are essential for refinancing where new lenders need to know how much to pay the existing lender. They provide the definitive settlement figure for loan discharge.',
        identificationRules: [
          'Look for "Redemption Statement", "Redemption Figure", or "Payoff Statement" in the title',
          'Shows total amount required to repay loan',
          'Includes redemption date (valid until date)',
          'Breaks down principal, interest, and fees',
          'May include early repayment charges',
          'Contains lender payment instructions',
          'Shows validity period',
          'May include daily interest rate for calculation adjustments',
          'Issued in response to redemption request',
        ],
        categoryRules:
          'Redemption Statements should be categorized under "Financial Documents" as they are loan settlement documents.',
      },
      {
        fileType: 'Completion Statement',
        category: 'Financial Documents',
        keywords: [
          'completion statement',
          'settlement statement',
          'completion figures',
          'closing statement',
          'purchase completion',
          'sale completion',
          'completion account',
          'final account',
          'apportionment',
        ],
        description:
          'Completion Statements are financial documents prepared for property transactions showing all amounts due on completion. They reconcile the purchase price with deposits paid, adjustments, apportionments, and amounts due to/from various parties. Completion Statements are prepared by solicitors and show the final figures for exchange or completion. They typically include purchase price, deposit already paid, balance due, stamp duty, legal fees, and apportionments for outgoings (rent, service charges, etc.). In development finance, completion statements are relevant when properties are sold, confirming sale proceeds and any amounts due to lenders from sales.',
        identificationRules: [
          'Look for "Completion Statement" or "Settlement Statement" in the title',
          'Shows financial summary of property transaction',
          'Includes purchase/sale price',
          'Shows deposit paid and balance due',
          'Contains apportionments for outgoings',
          'May include stamp duty and legal fees',
          'Prepared by solicitors',
          'Shows amounts due to/from each party',
          'Includes completion date',
        ],
        categoryRules:
          'Completion Statements should be categorized under "Financial Documents" as they are transaction settlement documents.',
      },
    ];

    const now = new Date().toISOString();
    // System defaults don't have a user - createdBy is optional

    // Check if definitions already exist
    const existing = await ctx.db.query("fileTypeDefinitions").collect();
    if (existing.length > 0) {
      console.log('File type definitions already exist, skipping seed');
      return { skipped: true, count: existing.length };
    }

    // Insert all definitions
    const insertedIds = [];
    for (const def of existingDefinitions) {
      const id = await ctx.db.insert("fileTypeDefinitions", {
        ...def,
        isSystemDefault: true,
        isActive: true,
        // createdBy omitted for system defaults
        createdAt: now,
        updatedAt: now,
      });
      insertedIds.push(id);
    }

    return { skipped: false, count: insertedIds.length, ids: insertedIds };
  },
});
