-- Schema for the Companies House charges reverse-lookup service.
-- Target: PostgreSQL (Render). Apply with: psql "$DATABASE_URL" -f app/schema.sql
--
-- One row per (charge, chargeholder). A charge with N persons-entitled becomes
-- N rows, so the lender index is naturally one-lender-per-row and reverse
-- lookup is a plain indexed predicate on `lender_canonical`.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS charges (
    -- IDENTITY (not BIGSERIAL): LIKE ... INCLUDING IDENTITY then gives the
    -- staging table its OWN sequence, so the post-swap DROP of the old table
    -- doesn't fail on a shared-sequence dependency.
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_number    TEXT        NOT NULL,   -- RN: the borrower's incorporation no.
    charge_id         TEXT        NOT NULL,   -- CC code (post-2013) or CN number (pre-2013)
    charge_id_type    TEXT        NOT NULL,   -- 'CC' | 'CN'
    lender_raw        TEXT        NOT NULL,   -- PE string as filed (chevrons/padding stripped)
    lender_canonical  TEXT        NOT NULL,   -- normalised key for grouping + exact match
    lender_crn        TEXT,                   -- company number embedded in the PE string, if any
    amount_secured    TEXT,                   -- AS: free text as filed (not numeric)
    description       TEXT,                   -- DM: charge description (e.g. "LEGAL CHARGE")
    property          TEXT,                   -- PP: particulars of property — often the scheme/address
    date_registered   DATE,
    date_created      DATE,
    fully_satisfied   BOOLEAN     NOT NULL DEFAULT FALSE,
    date_satisfied    DATE,
    jurisdiction      TEXT,                   -- 'ew' | 'sc' | 'ni'
    entity_type       TEXT,                   -- 'company' | 'llp'
    snapshot_run      INTEGER     NOT NULL,
    -- One charge can list the same lender once; guard against double-loads.
    UNIQUE (charge_id, lender_canonical)
);

-- Exact-match reverse lookup ("companies charged to PARAGON DEVELOPMENT FINANCE LIMITED").
CREATE INDEX IF NOT EXISTS idx_charges_lender_canonical ON charges (lender_canonical);

-- Fuzzy discovery ("what PARAGON-ish lenders exist?") via trigram similarity / ILIKE.
CREATE INDEX IF NOT EXISTS idx_charges_lender_trgm
    ON charges USING gin (lender_canonical gin_trgm_ops);

-- Forward lookup ("what charges does company X carry?") and CC-prefix joins.
CREATE INDEX IF NOT EXISTS idx_charges_company ON charges (company_number);

-- Filter to live / outstanding charges cheaply.
CREATE INDEX IF NOT EXISTS idx_charges_status ON charges (fully_satisfied);

-- Recency filtering for prospecting ("companies Lender X charged since 2024").
CREATE INDEX IF NOT EXISTS idx_charges_date_registered ON charges (date_registered);

-- Free-text property/scheme search ("developments in MANCHESTER").
CREATE INDEX IF NOT EXISTS idx_charges_property_trgm
    ON charges USING gin (property gin_trgm_ops);


-- Provenance: which snapshot the live data came from, surfaced as "data as of".
CREATE TABLE IF NOT EXISTS dataset_versions (
    id             SERIAL PRIMARY KEY,
    snapshot_run   INTEGER     NOT NULL,
    snapshot_date  DATE        NOT NULL,
    row_count      BIGINT      NOT NULL,
    source_files   TEXT,
    is_live        BOOLEAN     NOT NULL DEFAULT FALSE,  -- exactly one row true at a time
    loaded_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
