// =============================================================================
// PLANS — DOCUMENT REFERENCES
// =============================================================================
// Architectural and site drawings: floor plans, elevations, sections, site plans,
// location plans. These are primarily visual/graphical documents used in UK
// property development and lending.

import type { DocumentReference } from '../types';

export const PLAN_REFERENCES: DocumentReference[] = [
  // ---------------------------------------------------------------------------
  // 1. Floor Plans
  // ---------------------------------------------------------------------------
  {
    id: 'floor-plans',
    fileType: 'Floor Plans',
    category: 'Plans',
    filing: {
      targetFolder: 'Plans',
      targetLevel: 'project',
    },
    description:
      'Floor plans are horizontal architectural drawings that depict the layout of a building at a specific level, typically produced at scales of 1:50 or 1:100. Each plan represents a horizontal slice through the building at approximately one metre above the finished floor level, revealing the arrangement of rooms, corridors, walls, doors, windows, staircases, and structural elements. In UK property finance and development lending, floor plans are critical documents because they define the usable areas that underpin valuation and loan-to-value calculations. ' +
      'A complete set of floor plans for a development will include a plan for each storey — ground floor, first floor, second floor, and so on — plus any basement or roof-level plans where applicable. Each plan is annotated with room dimensions, door swing arcs, window positions, and functional labels such as bedroom, kitchen, bathroom, or reception. Hatching conventions distinguish load-bearing walls from partitions, and standard symbols denote fixtures like sinks, WCs, and radiators. ' +
      'The key measurements derived from floor plans are GIFA (Gross Internal Floor Area), NIA (Net Internal Area), and GIA (Gross Internal Area), all calculated according to the RICS Code of Measuring Practice or IPMS standards. These area figures feed directly into residual appraisals, development appraisals, and valuation reports. For residential schemes, floor plans show individual unit layouts that map to the accommodation schedule and sales brochure. For commercial properties, they show lettable areas, common parts, and service risers. ' +
      'Floor plans carry an architect or technician stamp, a unique drawing number (e.g., 1001, 1002), a revision letter or number (Rev A, Rev B), a scale bar, and a north point. They are typically issued as PDF or DWG files and may be produced by the project architect, planning consultant, or measured survey company.',
    identificationRules: [
      'PRIMARY: Horizontal architectural drawing showing internal room layouts, walls, doors, and windows at a specific building level',
      'PRIMARY: Contains room labels (bedroom, kitchen, living room, bathroom, hallway, reception) and internal dimensions',
      'CRITICAL: Shows a plan view (bird\'s-eye / top-down perspective) of a building interior — not an external site layout',
      'Includes hatching or line-weight conventions distinguishing structural walls from internal partitions',
      'Contains door swing arcs, window symbols, and staircase indicators with up/down arrows',
      'Annotated with floor area measurements (sqm or sqft) and room-by-room dimensions',
      'Title block references a specific floor level: "Ground Floor Plan", "First Floor Plan", "Basement Plan", "Roof Plan"',
      'Drawing scale is typically 1:50 or 1:100 with a printed scale bar',
      'May include furniture layouts, kitchen unit outlines, or sanitary ware symbols',
      'Carries an architect stamp, drawing number, and revision history',
      'Shows structural grid lines, column positions, or beam references where relevant',
    ],
    disambiguation: [
      'Floor Plans show the INTERNAL layout of a building at a specific level — if the drawing shows buildings arranged on a piece of land with boundaries and access roads, it is a Site Plan, not a Floor Plan.',
      'Floor Plans are graphical drawings, not tabular data. If the document is a spreadsheet or table listing unit types, bedroom counts, and areas, it is an Accommodation Schedule, not a Floor Plan.',
      'Floor Plans show a horizontal (plan) view. If the drawing shows the external face of a building from the side, it is an Elevation. If it shows a vertical cut through the building revealing internal heights, it is a Section.',
      'Floor Plans depict a single building level. If the drawing is a small-scale map showing the surrounding street context and OS mapping, it is a Location Plan.',
    ],
    terminology: {
      'GIFA': 'Gross Internal Floor Area — total floor area measured to the internal face of perimeter walls, including stairs, lifts, and common parts',
      'NIA': 'Net Internal Area — usable floor area excluding common parts, structural walls, staircases, and risers',
      'GIA': 'Gross Internal Area — floor area measured to the internal face of external walls, used for rating and building cost estimates',
      'Scale bar': 'Printed reference bar showing measured distances at the drawing scale, allowing verification even when printed at non-standard sizes',
      'North point': 'Orientation indicator showing the direction of true or grid north on the plan',
      'Revision': 'Amendment tracking identifier (Rev A, Rev B, etc.) recording changes to the drawing over time',
      'DWG': 'AutoCAD drawing file format, the industry-standard native format for architectural CAD drawings',
      'RICS Code of Measuring Practice': 'Industry standard published by the Royal Institution of Chartered Surveyors defining how building areas are calculated',
    },
    tags: [
      { namespace: 'type', value: 'floor-plans', weight: 1.0 },
      { namespace: 'domain', value: 'architecture', weight: 0.9 },
      { namespace: 'domain', value: 'property-development', weight: 0.8 },
      { namespace: 'signal', value: 'room-layout', weight: 0.9 },
      { namespace: 'signal', value: 'architectural-drawing', weight: 0.8 },
      { namespace: 'signal', value: 'floor-area-measurement', weight: 0.7 },
      { namespace: 'signal', value: 'plan-view', weight: 0.8 },
      { namespace: 'context', value: 'classification', weight: 0.9 },
      { namespace: 'context', value: 'filing', weight: 0.8 },
      { namespace: 'context', value: 'checklist', weight: 0.7 },
      { namespace: 'trigger', value: 'drawing+room-labels', weight: 0.9 },
    ],
    keywords: [
      'floor plan',
      'ground floor',
      'first floor',
      'second floor',
      'basement plan',
      'roof plan',
      'room layout',
      'bedroom',
      'kitchen',
      'bathroom',
      'living room',
      'GIFA',
      'NIA',
      'GIA',
      'gross internal floor area',
      'net internal area',
      'architect drawing',
      'door swing',
      'staircase',
      'partition wall',
      'scale 1:50',
      'scale 1:100',
      'proposed floor plan',
      'existing floor plan',
      'unit layout',
    ],
    filenamePatterns: [
      'floor[\\s_-]*plan',
      'ground[\\s_-]*floor',
      'first[\\s_-]*floor',
      'second[\\s_-]*floor',
      'basement[\\s_-]*plan',
      'GF[\\s_-]*plan',
      'FF[\\s_-]*plan',
      'SF[\\s_-]*plan',
      'proposed[\\s_-]*plan',
      'existing[\\s_-]*plan',
      'layout[\\s_-]*plan',
    ],
    excludePatterns: [
      'site[\\s_-]*plan',
      'location[\\s_-]*plan',
      'elevation',
      'section',
      'accommodation[\\s_-]*schedule',
      'area[\\s_-]*schedule',
    ],
    decisionRules: [
      {
        condition: 'Document shows internal room layout drawing with room labels and dimensions',
        signals: ['room-layout', 'architectural-drawing', 'plan-view'],
        priority: 9,
        action: 'include',
      },
      {
        condition: 'Title references a specific floor level (ground, first, basement, etc.)',
        signals: ['floor-level-title', 'plan-view'],
        priority: 8,
        action: 'boost',
      },
      {
        condition: 'Contains GIFA, NIA, or GIA area calculations alongside the drawing',
        signals: ['floor-area-measurement', 'architectural-drawing'],
        priority: 7,
        action: 'boost',
      },
      {
        condition: 'Document is a horizontal architectural plan with furniture layouts or sanitary ware symbols',
        signals: ['plan-view', 'furniture-layout'],
        priority: 6,
        action: 'include',
      },
    ],
    applicableContexts: ['classification', 'filing', 'chat', 'checklist'],
    expectedFields: [
      'drawing.number',
      'drawing.title',
      'drawing.revision',
      'drawing.scale',
      'drawing.date',
      'architect.name',
      'architect.practice',
      'areas.gifa',
      'areas.nia',
      'areas.gia',
      'project.name',
      'project.address',
    ],
    source: 'system',
    isActive: true,
    version: 1,
    updatedAt: '2026-02-24',
  },

  // ---------------------------------------------------------------------------
  // 2. Elevations
  // ---------------------------------------------------------------------------
  {
    id: 'elevations',
    fileType: 'Elevations',
    category: 'Plans',
    filing: {
      targetFolder: 'Plans',
      targetLevel: 'project',
    },
    description:
      'Elevations are architectural drawings that depict the external vertical faces of a building as viewed head-on from a fixed point at a distance. Each elevation represents one facade — typically labelled by orientation (north elevation, south elevation, east, west) or by context (front elevation, rear elevation, side elevation, street elevation). They are usually drawn at scales of 1:50 or 1:100, matching the floor plans for the same project, and form part of the statutory planning application package submitted to the local planning authority. ' +
      'An elevation drawing shows the external appearance of the building including the roof profile, ridge and eave lines, chimney stacks, window and door openings, external cladding materials, brickwork coursing, render finishes, rainwater goods, and any balconies or canopies. Finish materials are typically annotated or referenced to a materials schedule — for example "facing brick to match existing" or "through-coloured render, RAL 7016". Ground levels, finished floor levels, and ridge heights are dimensioned relative to an ordnance datum or site benchmark. ' +
      'In the context of UK property finance and development lending, elevations are reviewed by valuers, monitoring surveyors, and planners to assess the design quality, massing, visual impact, and compliance with planning conditions. They are compared against the approved planning drawings to verify that construction matches the consented scheme. Changes between approved and proposed elevations may indicate planning variations that require a section 73 or non-material amendment application. ' +
      'Elevations are distinct from sections: an elevation shows only what is visible on the external surface, whereas a section cuts through the building to reveal internal structure. A full set of elevations covers all principal facades and is cross-referenced to the floor plans and sections by a consistent drawing number series. Each sheet carries the architect stamp, drawing number, revision letter, scale bar, and project title.',
    identificationRules: [
      'PRIMARY: Architectural drawing showing the external face of a building viewed head-on from outside — a flat vertical projection of a facade',
      'PRIMARY: Labelled as a specific orientation or face: "North Elevation", "South Elevation", "Front Elevation", "Rear Elevation", "Street Elevation"',
      'CRITICAL: Shows external features only — roof lines, windows, doors, cladding materials, ground levels — NOT internal rooms or structure',
      'Contains material annotations: brick type, render colour, cladding specification, window frame material',
      'Shows dimensioned heights: finished floor levels (FFL), eave height, ridge height, relative to a datum',
      'Includes roof profile with ridge, eave, verge, hip, or gable details visible',
      'May show adjacent ground profile or neighbouring building outlines for context',
      'Drawing scale is typically 1:50 or 1:100 with a printed scale bar',
      'Carries an architect or design team stamp, drawing number, and revision letter',
      'Multiple elevations may appear on a single drawing sheet covering all facades',
      'Rainwater goods, flue terminals, meter boxes, and external fixtures may be indicated',
    ],
    disambiguation: [
      'Elevations show the EXTERNAL face of a building from outside. If the drawing shows a vertical cut through the building revealing internal rooms, floor structures, and ceiling voids, it is a Section, not an Elevation.',
      'Elevations are vertical views. If the drawing is a top-down view showing room layouts, it is a Floor Plan, not an Elevation.',
      'Elevations show a single building facade. If the drawing shows multiple buildings arranged on land with roads and boundaries, it is a Site Plan, not an Elevation.',
      'Elevations are architectural drawings. If the document is a photograph of a building exterior, it is a Photograph, not an Elevation.',
    ],
    terminology: {
      'FFL': 'Finished Floor Level — the height of the completed floor surface, typically given in metres above ordnance datum (AOD)',
      'Ridge height': 'The highest point of a pitched roof, measured from ground level or ordnance datum',
      'Eave height': 'The point where the roof meets the external wall, marking the transition from wall to roof structure',
      'Ordnance datum': 'The national height reference system (Ordnance Datum Newlyn) used on UK construction drawings to express absolute levels',
      'Section 73': 'A planning application to vary or remove conditions on an existing planning permission, often used for design changes',
      'Non-material amendment': 'A minor change to an approved planning permission that does not materially alter the scheme',
      'Cladding': 'External wall covering material — brick, render, timber, metal panel, stone, etc.',
      'Rainwater goods': 'Gutters, downpipes, hoppers, and associated fittings for roof drainage',
    },
    tags: [
      { namespace: 'type', value: 'elevations', weight: 1.0 },
      { namespace: 'domain', value: 'architecture', weight: 0.9 },
      { namespace: 'domain', value: 'property-development', weight: 0.8 },
      { namespace: 'signal', value: 'facade-drawing', weight: 0.9 },
      { namespace: 'signal', value: 'architectural-drawing', weight: 0.8 },
      { namespace: 'signal', value: 'external-materials', weight: 0.7 },
      { namespace: 'signal', value: 'height-dimensions', weight: 0.7 },
      { namespace: 'context', value: 'classification', weight: 0.9 },
      { namespace: 'context', value: 'filing', weight: 0.8 },
      { namespace: 'context', value: 'checklist', weight: 0.7 },
      { namespace: 'trigger', value: 'drawing+facade-labels', weight: 0.9 },
    ],
    keywords: [
      'elevation',
      'front elevation',
      'rear elevation',
      'side elevation',
      'north elevation',
      'south elevation',
      'east elevation',
      'west elevation',
      'street elevation',
      'facade',
      'ridge height',
      'eave height',
      'finished floor level',
      'FFL',
      'cladding',
      'brickwork',
      'render',
      'roof profile',
      'window openings',
      'external appearance',
      'proposed elevations',
      'existing elevations',
      'materials schedule',
      'ordnance datum',
    ],
    filenamePatterns: [
      'elevation',
      'front[\\s_-]*elev',
      'rear[\\s_-]*elev',
      'side[\\s_-]*elev',
      'north[\\s_-]*elev',
      'south[\\s_-]*elev',
      'east[\\s_-]*elev',
      'west[\\s_-]*elev',
      'street[\\s_-]*elev',
      'proposed[\\s_-]*elev',
      'existing[\\s_-]*elev',
    ],
    excludePatterns: [
      'section',
      'floor[\\s_-]*plan',
      'site[\\s_-]*plan',
      'location[\\s_-]*plan',
      'photograph',
      'photo',
    ],
    decisionRules: [
      {
        condition: 'Drawing shows external building facade with material annotations and height dimensions',
        signals: ['facade-drawing', 'external-materials', 'height-dimensions'],
        priority: 9,
        action: 'include',
      },
      {
        condition: 'Title contains directional or contextual elevation label (North, Front, Rear, Street)',
        signals: ['elevation-title', 'facade-drawing'],
        priority: 8,
        action: 'boost',
      },
      {
        condition: 'Shows roof profile, window openings, and door positions from external view',
        signals: ['facade-drawing', 'architectural-drawing'],
        priority: 7,
        action: 'include',
      },
      {
        condition: 'Contains FFL, ridge, and eave level annotations',
        signals: ['height-dimensions', 'ordnance-datum'],
        priority: 6,
        action: 'boost',
      },
    ],
    applicableContexts: ['classification', 'filing', 'chat', 'checklist'],
    expectedFields: [
      'drawing.number',
      'drawing.title',
      'drawing.revision',
      'drawing.scale',
      'drawing.date',
      'architect.name',
      'architect.practice',
      'heights.ridge',
      'heights.eave',
      'heights.ffl',
      'project.name',
      'project.address',
    ],
    source: 'system',
    isActive: true,
    version: 1,
    updatedAt: '2026-02-24',
  },

  // ---------------------------------------------------------------------------
  // 3. Sections
  // ---------------------------------------------------------------------------
  {
    id: 'sections',
    fileType: 'Sections',
    category: 'Plans',
    filing: {
      targetFolder: 'Plans',
      targetLevel: 'project',
    },
    description:
      'Sections are architectural drawings that depict a building as if it has been sliced vertically along a defined cutting plane, revealing the internal structure, floor-to-ceiling heights, roof construction, and the relationship between different storeys. The cutting line is indicated on the corresponding floor plan with a labelled reference such as A-A, B-B, or 1-1, with arrows showing the direction of view. Sections are typically drawn at scales of 1:50 or 1:100 and form an essential part of both planning application submissions and building regulations packages. ' +
      'A section drawing shows the full vertical profile of the building from foundation to ridge. It exposes floor slab thicknesses, ceiling heights, structural beams and columns, roof trusses or rafters, insulation zones, and damp-proof courses. Where the cutting plane passes through solid structure — walls, floors, roofs — the cut material is shown with dense hatching or fill to distinguish it from elements seen beyond the cut. Rooms on either side of the cut are visible in the background, providing spatial context. ' +
      'In UK property finance and development lending, sections are reviewed by monitoring surveyors to verify that construction matches approved drawings, by valuers to confirm storey heights and habitable space, and by building control officers to check compliance with Approved Documents (Part B fire, Part E sound, Part L thermal performance). Floor-to-floor heights are critical for establishing whether mezzanine levels, loft conversions, or basement excavations meet minimum headroom requirements. Sections also reveal the ground-to-building relationship — showing how the building sits relative to external ground levels, drainage invert levels, and any retaining wall structures. ' +
      'A complete set of sections typically includes at least one longitudinal section and one cross section. Complex buildings may have multiple sections at different positions. Each sheet carries the architect stamp, drawing number, revision letter, scale bar, and section reference designation. Sections are cross-referenced to the floor plans and elevations through a consistent drawing number series.',
    identificationRules: [
      'PRIMARY: Architectural drawing showing a building cut vertically to reveal internal structure, floor levels, and heights across multiple storeys',
      'PRIMARY: Labelled with a section reference line such as "Section A-A", "Section B-B", "Section 1-1" or "Cross Section"',
      'CRITICAL: Shows CUT-THROUGH material with hatching or fill — distinguishing it from elevations which show only external surfaces',
      'Reveals floor-to-ceiling heights, floor slab thicknesses, and roof construction within the same drawing',
      'Shows foundation details, damp-proof courses, and the relationship between ground level and the building',
      'Contains level annotations: finished floor levels (FFL), ceiling heights, ridge and eave levels',
      'Structural elements (beams, columns, roof trusses, lintels) are visible in the cut plane',
      'The cutting plane direction is referenced to a corresponding floor plan with arrows and a label',
      'Drawing scale is typically 1:50 or 1:100 with a printed scale bar',
      'May show insulation zones, cavity widths, and wall build-up details in the cut material',
      'Carries an architect or structural engineer stamp, drawing number, and revision letter',
    ],
    disambiguation: [
      'Sections show a VERTICAL CUT through the building revealing internal structure. If the drawing shows only the external face of the building without cutting through it, it is an Elevation, not a Section.',
      'Sections are vertical cuts. If the drawing shows a horizontal (top-down) view of room layouts at a single level, it is a Floor Plan, not a Section.',
      'Sections show building construction detail. If the drawing shows buildings arranged on land with boundaries and roads, it is a Site Plan, not a Section.',
      'Sections show the whole building cut through. If the drawing is a very detailed close-up showing wall construction layers, flashing details, or junction details at a large scale (1:5 or 1:10), it may be a Construction Detail rather than a Section.',
    ],
    terminology: {
      'Section line': 'A labelled line drawn on the floor plan (e.g., A-A, B-B) indicating where the vertical cut is taken and which direction the section looks',
      'Hatching': 'Dense line fill applied to material that has been cut through, distinguishing solid structure from void or background elements',
      'Floor-to-floor height': 'The vertical distance from one finished floor level to the next, encompassing ceiling height plus structural floor zone',
      'DPC': 'Damp-Proof Course — a horizontal barrier within a wall to prevent moisture rising from the ground into the building fabric',
      'Roof truss': 'A prefabricated structural frame that supports the roof covering, visible in section drawings as triangulated timber or steel members',
      'Approved Document': 'Technical guidance documents supporting the Building Regulations in England and Wales (Part A Structure, Part B Fire, Part L Conservation of Fuel, etc.)',
      'Invert level': 'The lowest internal point of a pipe or drain, used to describe drainage falls and connections',
      'Retaining wall': 'A wall designed to hold back earth or water, often visible in sections where ground levels change',
    },
    tags: [
      { namespace: 'type', value: 'sections', weight: 1.0 },
      { namespace: 'domain', value: 'architecture', weight: 0.9 },
      { namespace: 'domain', value: 'property-development', weight: 0.8 },
      { namespace: 'signal', value: 'vertical-cut-drawing', weight: 0.9 },
      { namespace: 'signal', value: 'architectural-drawing', weight: 0.8 },
      { namespace: 'signal', value: 'section-reference-line', weight: 0.9 },
      { namespace: 'signal', value: 'height-dimensions', weight: 0.7 },
      { namespace: 'context', value: 'classification', weight: 0.9 },
      { namespace: 'context', value: 'filing', weight: 0.8 },
      { namespace: 'context', value: 'checklist', weight: 0.7 },
      { namespace: 'trigger', value: 'drawing+section-label', weight: 0.9 },
    ],
    keywords: [
      'section',
      'cross section',
      'longitudinal section',
      'section A-A',
      'section B-B',
      'section 1-1',
      'building section',
      'floor to ceiling height',
      'floor to floor height',
      'roof construction',
      'foundation',
      'damp proof course',
      'DPC',
      'roof truss',
      'structural section',
      'hatching',
      'cut through',
      'internal heights',
      'proposed section',
      'existing section',
      'insulation',
      'cavity wall',
      'floor slab',
      'ridge level',
    ],
    filenamePatterns: [
      'section',
      'cross[\\s_-]*section',
      'long[\\s_-]*section',
      'sect[\\s_-]*[A-Z]-[A-Z]',
      'sect[\\s_-]*\\d+-\\d+',
      'building[\\s_-]*section',
      'proposed[\\s_-]*section',
      'existing[\\s_-]*section',
    ],
    excludePatterns: [
      'elevation',
      'floor[\\s_-]*plan',
      'site[\\s_-]*plan',
      'location[\\s_-]*plan',
      'detail[\\s_-]*section',
      'construction[\\s_-]*detail',
    ],
    decisionRules: [
      {
        condition: 'Drawing shows a vertical cut through a building with hatched structural elements and internal heights',
        signals: ['vertical-cut-drawing', 'section-reference-line', 'height-dimensions'],
        priority: 9,
        action: 'include',
      },
      {
        condition: 'Title contains section reference label (Section A-A, Cross Section, Longitudinal Section)',
        signals: ['section-reference-line', 'architectural-drawing'],
        priority: 8,
        action: 'boost',
      },
      {
        condition: 'Shows foundation-to-ridge profile with floor slab thicknesses and ceiling heights',
        signals: ['vertical-cut-drawing', 'height-dimensions'],
        priority: 7,
        action: 'include',
      },
      {
        condition: 'Contains hatching on cut material with construction build-up annotations',
        signals: ['vertical-cut-drawing', 'construction-detail'],
        priority: 6,
        action: 'boost',
      },
    ],
    applicableContexts: ['classification', 'filing', 'chat', 'checklist'],
    expectedFields: [
      'drawing.number',
      'drawing.title',
      'drawing.revision',
      'drawing.scale',
      'drawing.date',
      'architect.name',
      'architect.practice',
      'section.reference',
      'heights.floorToFloor',
      'heights.floorToCeiling',
      'heights.ridge',
      'project.name',
      'project.address',
    ],
    source: 'system',
    isActive: true,
    version: 1,
    updatedAt: '2026-02-24',
  },

  // ---------------------------------------------------------------------------
  // 4. Site Plans
  // ---------------------------------------------------------------------------
  {
    id: 'site-plans',
    fileType: 'Site Plans',
    category: 'Plans',
    filing: {
      targetFolder: 'Plans',
      targetLevel: 'project',
    },
    description:
      'Site plans are scaled drawings that show the arrangement of buildings, structures, and external works on a specific piece of land, typically drawn at scales of 1:200 or 1:500. They form a mandatory component of UK planning applications and are the primary drawing used to understand how a development sits within its plot and relates to adjacent properties, roads, and infrastructure. The site is usually delineated by a red line boundary (the application site) and may include a blue line boundary indicating land in the same ownership but outside the application. ' +
      'A site plan shows the footprint of existing and proposed buildings, vehicular and pedestrian access points, parking layouts (including disabled bays and cycle stores), hard and soft landscaping, boundary treatments (fences, walls, hedges), refuse and recycling storage, drainage runs, and any external plant or service compound areas. Finished floor levels and external ground levels are annotated to demonstrate how the development responds to the topography. Tree positions, root protection areas, and landscaping zones may also appear, particularly where a tree preservation order or ecological constraint applies. ' +
      'In UK property finance and development lending, site plans are reviewed by valuers to assess site coverage ratios and density, by monitoring surveyors to track construction progress against the approved layout, and by solicitors to check that the red line boundary aligns with the title plan. Planning officers use the site plan to evaluate access arrangements, overlooking distances, amenity space provision, and compliance with local parking standards. ' +
      'Site plans are distinct from location plans: a site plan shows detailed layout at a large scale (typically 1:200 to 1:500) whereas a location plan shows the wider geographic context at a small scale (1:1250 or 1:2500). Site plans are also distinct from floor plans, which show the internal room layout of a building rather than the external arrangement of buildings on land. Each site plan carries an architect stamp, drawing number, revision letter, scale bar, and north point.',
    identificationRules: [
      'PRIMARY: Drawing showing the arrangement of buildings, access roads, parking, and landscaping on a plot of land — external site layout, not internal building layout',
      'PRIMARY: Contains a red line boundary delineating the application or development site area',
      'CRITICAL: Scale is typically 1:200 or 1:500 — larger and more detailed than a location plan but not showing internal room layouts',
      'Shows building footprints (outlines) rather than internal room arrangements',
      'Includes vehicular access points, parking bays, turning circles, and pedestrian routes',
      'Contains boundary treatment annotations: fences, walls, hedges, gates',
      'Shows hard landscaping (paving, tarmac) and soft landscaping (planting, grass) areas',
      'Annotated with finished floor levels, external ground levels, or spot heights',
      'May include drainage routes, manholes, service connections, or utility runs',
      'Contains a north point and scale bar, with the site filling most of the drawing sheet',
      'Carries an architect or landscape architect stamp, drawing number, and revision letter',
    ],
    disambiguation: [
      'Site Plans show the EXTERNAL arrangement of buildings on land. If the drawing shows internal room layouts within a building (bedrooms, kitchens, corridors), it is a Floor Plan, not a Site Plan.',
      'Site Plans are detailed and drawn at large scales (1:200 to 1:500). If the drawing is a small-scale map (1:1250 or 1:2500) showing the wider street context with OS base mapping, it is a Location Plan, not a Site Plan.',
      'Site Plans show plan-view layout. If the drawing shows a building facade from the side, it is an Elevation. If it shows a vertical cut through a building, it is a Section.',
      'Site Plans are drawings with precise measurements. If the document is a satellite or aerial photograph of the site, it is a Photograph or Aerial Image, not a Site Plan.',
    ],
    terminology: {
      'Red line boundary': 'The line drawn around the planning application site, enclosing all land where development is proposed — a mandatory requirement for UK planning applications',
      'Blue line boundary': 'A line drawn around land in the same ownership as the application site but outside the red line, required to be shown on planning application site plans',
      'Site coverage': 'The proportion of the total site area occupied by building footprints, expressed as a percentage',
      'Turning circle': 'The area required for a vehicle (typically a refuse truck or fire tender) to turn around within the site without reversing onto the public highway',
      'Root protection area': 'A calculated zone around a tree trunk within which development or ground disturbance is restricted to protect tree health (defined by BS 5837)',
      'Boundary treatment': 'The means of enclosure at the site edges and between plots — fencing, walls, hedgerows, railings, etc.',
      'Spot height': 'A point on the drawing annotated with its level (height above ordnance datum), used to describe the topography of the site',
      'Amenity space': 'Private or communal outdoor space provided for the use of occupants, assessed by planners for adequacy',
    },
    tags: [
      { namespace: 'type', value: 'site-plans', weight: 1.0 },
      { namespace: 'domain', value: 'architecture', weight: 0.8 },
      { namespace: 'domain', value: 'property-development', weight: 0.9 },
      { namespace: 'domain', value: 'planning', weight: 0.9 },
      { namespace: 'signal', value: 'site-layout', weight: 0.9 },
      { namespace: 'signal', value: 'red-line-boundary', weight: 0.9 },
      { namespace: 'signal', value: 'parking-layout', weight: 0.7 },
      { namespace: 'signal', value: 'architectural-drawing', weight: 0.7 },
      { namespace: 'context', value: 'classification', weight: 0.9 },
      { namespace: 'context', value: 'filing', weight: 0.8 },
      { namespace: 'context', value: 'checklist', weight: 0.7 },
      { namespace: 'trigger', value: 'drawing+site-boundary', weight: 0.9 },
    ],
    keywords: [
      'site plan',
      'site layout',
      'block plan',
      'red line boundary',
      'blue line boundary',
      'parking layout',
      'access road',
      'vehicular access',
      'pedestrian access',
      'landscaping',
      'boundary treatment',
      'building footprint',
      'site coverage',
      'turning circle',
      'refuse storage',
      'cycle storage',
      'amenity space',
      'proposed site plan',
      'existing site plan',
      'scale 1:200',
      'scale 1:500',
      'hard landscaping',
      'soft landscaping',
      'spot height',
    ],
    filenamePatterns: [
      'site[\\s_-]*plan',
      'site[\\s_-]*layout',
      'block[\\s_-]*plan',
      'proposed[\\s_-]*site',
      'existing[\\s_-]*site',
      'site[\\s_-]*GA',
      'general[\\s_-]*arrangement',
      'landscape[\\s_-]*plan',
      'parking[\\s_-]*layout',
    ],
    excludePatterns: [
      'location[\\s_-]*plan',
      'floor[\\s_-]*plan',
      'elevation',
      'section',
      'OS[\\s_-]*map',
      'ordnance[\\s_-]*survey',
    ],
    decisionRules: [
      {
        condition: 'Drawing shows buildings arranged on land with red line boundary, access, and parking',
        signals: ['site-layout', 'red-line-boundary', 'parking-layout'],
        priority: 9,
        action: 'include',
      },
      {
        condition: 'Title references "Site Plan", "Site Layout", or "Block Plan"',
        signals: ['site-plan-title', 'site-layout'],
        priority: 8,
        action: 'boost',
      },
      {
        condition: 'Scale is 1:200 or 1:500 showing external site arrangement, not internal rooms',
        signals: ['site-layout', 'medium-scale'],
        priority: 7,
        action: 'include',
      },
      {
        condition: 'Contains boundary treatments, landscaping zones, and external level annotations',
        signals: ['site-layout', 'landscaping'],
        priority: 6,
        action: 'boost',
      },
    ],
    applicableContexts: ['classification', 'filing', 'chat', 'checklist'],
    expectedFields: [
      'drawing.number',
      'drawing.title',
      'drawing.revision',
      'drawing.scale',
      'drawing.date',
      'architect.name',
      'architect.practice',
      'site.area',
      'site.coverage',
      'parking.spaces',
      'project.name',
      'project.address',
    ],
    source: 'system',
    isActive: true,
    version: 1,
    updatedAt: '2026-02-24',
  },

  // ---------------------------------------------------------------------------
  // 5. Location Plans
  // ---------------------------------------------------------------------------
  {
    id: 'location-plans',
    fileType: 'Location Plans',
    category: 'Plans',
    filing: {
      targetFolder: 'Plans',
      targetLevel: 'project',
    },
    description:
      'Location plans are small-scale maps that show the wider geographic context of a development site, typically drawn at scales of 1:1250 or 1:2500 using Ordnance Survey (OS) base mapping. They are a mandatory requirement for UK planning applications under Article 7 of the Town and Country Planning (Development Management Procedure) Order, and must show at least two named roads and surrounding buildings or land to enable the local planning authority to identify the precise location of the proposed development. The application site is outlined in red (the red line boundary), and any adjoining land owned by the applicant is outlined in blue. ' +
      'Location plans are distinguished from site plans by their scale and level of detail. Where a site plan shows the detailed arrangement of buildings, access, and landscaping within the development at 1:200 or 1:500, a location plan shows the surrounding streets, neighbouring properties, public open spaces, watercourses, and local landmarks at 1:1250 or 1:2500. The base mapping is reproduced under Ordnance Survey licence and carries the OS copyright acknowledgement and licence number. The site outline is typically a simple red rectangle or polygon superimposed on the OS map base. ' +
      'In UK property finance and development lending, location plans are used by solicitors to cross-reference the application site against the registered title plan held at HM Land Registry, ensuring that the borrower owns the land they intend to develop. Valuers use location plans to assess the site context — proximity to transport links, local amenities, flood zones, and conservation areas. Monitoring surveyors reference the location plan to find the site on their first visit. ' +
      'Location plans carry a north point, scale bar, OS licence number, and the site address. They are often the simplest drawing in a planning set but serve the essential function of placing the development in its geographic context. The red line on the location plan must match the red line on the site plan exactly.',
    identificationRules: [
      'PRIMARY: Small-scale map (1:1250 or 1:2500) showing the wider area around a development site with OS base mapping',
      'PRIMARY: Contains a red line boundary outlining the application site on an Ordnance Survey map background',
      'CRITICAL: Uses OS base mapping with recognisable features — street names, building outlines, plot boundaries, footpaths — this is a MAP, not an architectural drawing',
      'Scale is 1:1250 or 1:2500 — much smaller scale than a site plan, showing a wider area',
      'Shows at least two named roads surrounding the site for identification purposes',
      'Contains an Ordnance Survey copyright notice and licence number',
      'The site is indicated as a simple outlined polygon (usually red) on the map, not a detailed layout',
      'Shows neighbouring properties, streets, gardens, and local context at the map scale',
      'May include a blue line boundary indicating adjoining land in the same ownership',
      'Carries a north point and scale bar, and is titled "Location Plan" or "Site Location Plan"',
      'Does not show internal building layouts, parking bays, or landscaping details — these belong on the site plan',
    ],
    disambiguation: [
      'Location Plans show the WIDER GEOGRAPHIC CONTEXT at small scale (1:1250 or 1:2500) using OS mapping. If the drawing shows detailed buildings, parking, and landscaping on the site at 1:200 or 1:500, it is a Site Plan, not a Location Plan.',
      'Location Plans use OS base mapping (grey/black printed map background). If the drawing is a bespoke architectural drawing showing building footprints with design detail, it is likely a Site Plan.',
      'Location Plans show the site as a simple outlined polygon. If the drawing shows internal room layouts within a building, it is a Floor Plan, not a Location Plan.',
      'Location Plans are maps, not photographs. If the document is a satellite image or aerial photograph showing the site from above, it is an Aerial Photograph, not a Location Plan.',
    ],
    terminology: {
      'Ordnance Survey': 'The UK national mapping agency, whose base mapping is the standard background for location plans in planning applications',
      'OS licence': 'A commercial licence permitting reproduction of Ordnance Survey mapping data, required for planning application location plans',
      'Red line boundary': 'The boundary of the planning application site drawn on the location plan — must encompass all land where development is proposed',
      'Blue line boundary': 'Land in the same ownership as the applicant adjoining the application site, required to be outlined in blue',
      'Title plan': 'The plan held at HM Land Registry showing the extent of a registered freehold or leasehold title, often compared against the location plan red line',
      'Article 7': 'The article in the Town and Country Planning (Development Management Procedure) Order that specifies the plan requirements for valid planning applications',
      'Scale 1:1250': 'A map scale where 1mm on paper represents 1.25 metres on the ground — the standard scale for location plans in urban areas',
      'Scale 1:2500': 'A map scale where 1mm on paper represents 2.5 metres on the ground — the standard scale for location plans in rural areas',
    },
    tags: [
      { namespace: 'type', value: 'location-plans', weight: 1.0 },
      { namespace: 'domain', value: 'planning', weight: 0.9 },
      { namespace: 'domain', value: 'property-development', weight: 0.8 },
      { namespace: 'signal', value: 'os-mapping', weight: 0.9 },
      { namespace: 'signal', value: 'red-line-boundary', weight: 0.8 },
      { namespace: 'signal', value: 'small-scale-map', weight: 0.9 },
      { namespace: 'signal', value: 'geographic-context', weight: 0.7 },
      { namespace: 'context', value: 'classification', weight: 0.9 },
      { namespace: 'context', value: 'filing', weight: 0.8 },
      { namespace: 'context', value: 'checklist', weight: 0.7 },
      { namespace: 'trigger', value: 'map+red-line+os-mapping', weight: 0.9 },
    ],
    keywords: [
      'location plan',
      'site location plan',
      'Ordnance Survey',
      'OS map',
      'OS mapping',
      'red line boundary',
      'blue line boundary',
      'scale 1:1250',
      'scale 1:2500',
      'OS licence',
      'OS copyright',
      'planning application',
      'named roads',
      'surrounding area',
      'geographic context',
      'title plan',
      'HM Land Registry',
      'site identification',
      'wider area',
      'neighbouring properties',
      'application site',
      'north point',
    ],
    filenamePatterns: [
      'location[\\s_-]*plan',
      'site[\\s_-]*location',
      'OS[\\s_-]*plan',
      'OS[\\s_-]*map',
      'ordnance[\\s_-]*survey',
      'loc[\\s_-]*plan',
    ],
    excludePatterns: [
      'site[\\s_-]*plan',
      'site[\\s_-]*layout',
      'floor[\\s_-]*plan',
      'elevation',
      'section',
      'block[\\s_-]*plan',
    ],
    decisionRules: [
      {
        condition: 'Map at 1:1250 or 1:2500 scale with OS base mapping and red line site boundary',
        signals: ['os-mapping', 'red-line-boundary', 'small-scale-map'],
        priority: 9,
        action: 'include',
      },
      {
        condition: 'Title contains "Location Plan" or "Site Location Plan"',
        signals: ['location-plan-title', 'os-mapping'],
        priority: 8,
        action: 'boost',
      },
      {
        condition: 'Shows surrounding streets and properties at map scale with OS copyright notice',
        signals: ['os-mapping', 'geographic-context'],
        priority: 7,
        action: 'include',
      },
      {
        condition: 'Contains OS licence number and shows at least two named roads',
        signals: ['os-mapping', 'small-scale-map'],
        priority: 6,
        action: 'boost',
      },
    ],
    applicableContexts: ['classification', 'filing', 'chat', 'checklist'],
    expectedFields: [
      'drawing.title',
      'drawing.scale',
      'drawing.date',
      'site.address',
      'os.licenceNumber',
      'boundaries.redLine',
      'boundaries.blueLine',
      'project.name',
      'project.address',
    ],
    source: 'system',
    isActive: true,
    version: 1,
    updatedAt: '2026-02-24',
  },
];
